jrprice/Oclgrind

- src/plugins/MemCheck.cpp
- src/plugins/MemCheck.h
- tests/kernels/TESTS
- tests/kernels/memcheck/fake_out_of_bounds.cl
- tests/kernels/memcheck/fake_out_of_bounds.ref
- tests/kernels/memcheck/fake_out_of_bounds.sim
- tests/kernels/memcheck/static_array.cl
- tests/kernels/memcheck/static_array.ref
- tests/kernels/memcheck/static_array.sim
This pull request improves the check for out of bound arrays accesses. The previous check did always evaluate the indices of the getelementptr instruction which leads to false positives. The gep instruction can be used to compute addresses which would allegedly violate the static bounds of an array without introducing undefined behaviour (See http://llvm.org/docs/GetElementPtr.html#what-happens-if-an-array-index-is-out-of-bounds and the test memcheck/fake_out_of_bounds).
The behaviour of the check is changed such that now the gep instruction is only evaluated if it is used as operand in a load or store instruction. Only in this cases the address is actually used to access memory which could create an invalid access.
> More precise index out of bounds check

- src/plugins/MemCheck.cpp
- tests/kernels/TESTS
- tests/kernels/memcheck/casted_static_array.cl
- tests/kernels/memcheck/casted_static_array.ref
- tests/kernels/memcheck/casted_static_array.sim
I figured out that Oclgrind misses some static out-of-bound accesses due to the SROA optimisation. In these situations the GEP value is casted before the load/store operation which causes Oclgrind not to perform a check.
I added "stripPointerCasts()" to ignore all cast between load/store and GEP instruction.
> Ignore casts when checking static array bounds

- src/plugins/Uninitialized.cpp
- src/plugins/Uninitialized.h
- tests/kernels/TESTS
- tests/kernels/bugs/false_warning_vector_argument.cl
- tests/kernels/bugs/false_warning_vector_argument.ref
- tests/kernels/bugs/false_warning_vector_argument.sim
I discovered that there might be situations where the compiler seems to choose a larger vector size and fills it with `undef` values.
Since until now vector elements where not handled separately this lead to false positive warnings in cases where the `undef` elements were actually not used.
For instance:
```
%115 = add <16 x i32> %114, <i32 -162813643, i32 -162813643, i32 -162813643, i32 -162813643, i32 -162813643, i32 -162813643, i32 -162813643, i32 -162813643, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
%116 = shufflevector <16 x i32> %115, <16 x i32> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
store <8 x i32> %116, <8 x i32>* %0, align 32, !tbaa !16
```
The previous handling caused all elements of the shadow …
> More precise check for vector arguments

- src/runtime/oclgrind
I notices the the oclgrind wrapper script does not forward the SIGTERM command to the actual executable. For instance, trying to kill the oclgrind process in htop only results in the bash being killed but the actual executable continues to run. (Ctrl-C does kill both but I've read that it works slightly different than just sending SIGTERM.)
I added exec before the call to the actual executable in the oclgrind script which solves the problem. The bash is replaced by the actual program and thus there is only one process which has to be killed.
> Kill program if Oclgrind is killed

- src/plugins/MemCheck.cpp
I've noticed that when a kernel is using __private (indexed) or __local memory oclgrind reports the following false positives...
* "Invalid write to mapped buffer"
* "Invalid read from buffer mapped for writing"
This request attempts to fix this by simply not checking for mapped memory if address space is private/local.
> Fix MemCheck mapped memory check

- src/core/Memory.cpp
- src/core/Memory.h
- src/core/WorkItemBuiltins.cpp
The following function was producing wrong results for signed values and min/max operators
`uint32_t Memory::atomic(AtomicOp op, size_t address, uint32_t value);`
This merge request is converting the method to a template
`template<typename T> T Memory::atomic(AtomicOp op, size_t address, T value);`
with four forward declared versions...
```
template uint32_t Memory::atomic(AtomicOp op, size_t address, uint32_t value);
template int32_t Memory::atomic(AtomicOp op, size_t address, int32_t value);
template uint64_t Memory::atomic(AtomicOp op, size_t address, uint64_t value);
template int64_t Memory::atomic(AtomicOp op, size_t address, int64_t value);
```
In WorkitemsBuiltins.cpp I am trying to determine where the type is signed or not and call the proper version.
I am not sure about the way I …
> Fix atomic_min/max

- src/core/Program.cpp
for LLVM_VERSION >= 40 use -cl-ext to control the supported OpenCL extensions explicitly and be able to do something like the following in the kernel code...
```
#ifdef cl_khr_fp16
...
#endif
```
> add -cl-ext support

- src/runtime/runtime.cpp
Memory may be allocated for context properties [here](https://github.com/jrprice/Oclgrind/blob/master/src/runtime/runtime.cpp#L874). However, this memory is never released when deleting a context. The proposed fix checks if this memory was allocated, and if so, frees it.
All runtime tests pass.
> Fix memory leak in context properties

- src/runtime/runtime.cpp
Fixes two issues highlighted by Valgrind:
* "Conditional jump or move depends on uninitialised value(s)" on
clReleaseSampler (runtime.cpp:2116)
* Memory leak when using samplers, since these were not properly
released
> Add missing reference count initialization for sampler objects

- src/core/Queue.h
Instances of derived command structs with destructors were not being freed since the Command base struct didn't have a virtual destructor.
Found this when adding a destructor to the FillImageCommand struct, and noticing that it was not being invoked.
I initially added this destructor due to an invalid read size valgrind warning in the following instruction:
```cpp
memcpy(color, col, 16);
```
Size of color object may not be 16 (it depends on pixel size), thus the warning. As such, the color object is now dynamically allocated depending on the pixel size, and destroyed in the respective destructor.
> Fix memory leaks when releasing commands

- src/core/common.h
- src/runtime/icd.h
- src/runtime/runtime.cpp
When passing an image as a kernel argument, memory is allocated for a `oclgrind::Image struct`. This memory was not being released.
The proposed fix keeps a record of these objects in the respective kernel instance (`_cl_kernel`), and releases them when the kernel instance is destroyed.
> Fix memory leaks when passing images as kernel arguments

- src/core/Kernel.cpp
By fixing issue #169, part of the same problem moved from `Program` to `Kernel`, now occurring when creating a `Kernel` from another kernel with the `Kernel(const Kernel& kernel)` constructor.
The proposed fix simply adds the check for uniform work-groups to the `Kernel(const Kernel& kernel)` constructor. Since the same check is now made in both `Kernel` constructors, the associated code has been moved to a private method.
This is a pretty naive fix, so feel free to reject the PR or suggest a proper way to solve the issue.
Thanks
> Fix uninitialised value Kernel::m_requiresUniformWorkGroups

- src/runtime/runtime.cpp
In Oclgrind some image OpenCL API functions use buffer functions to complete their work. However, the image functions don't check for errors thrown by the buffer functions and always try to modify the corresponding event. Since an event is not created when the buffer functions throw errors, the image functions try to modify an invalid memory block, expecting it to contain an event, resulting in a segmentation fault.
This fix checks if errors are thrown by buffer functions before modifying the corresponding event in the calling image functions.
> Fix segfaults when modifying event type in image API functions

- src/runtime/runtime.cpp
According to the OpenCL reference, the `clEnqueueCopyBufferRect()` function should return `CL_INVALID_VALUE` "if any region array element is 0." There's also check for a `NULL` region, although this is not explicit in the documentation.
> Add check for invalid region in clEnqueueCopyBufferRect

- src/runtime/runtime.cpp
In `clEnqueueUnmapMemObject()` documentation: "`CL_INVALID_VALUE` if `mapped_ptr` is not a valid pointer returned by `clEnqueueMapBuffer` or `clEnqueueMapImage` for `memobj`."
> Add check for invalid mapped pointer when unmapping memory objects

- src/runtime/runtime.cpp
The incorrect command type was being assigned to the events generated by the `clEnqueueRead/Write/CopyBufferRect()` runtime functions.
> Fix read/write/copy rect command types

- src/core/Queue.cpp
- src/core/Queue.h
- src/runtime/async_queue.cpp
- src/runtime/async_queue.h
- src/runtime/icd.h
- src/runtime/runtime.cpp
- tests/common/common.c
- tests/common/common.h
- tests/runtime/CMakeLists.txt
- tests/runtime/multqueues.c
- tests/runtime/multqueues.ref
This proposal adds support for multiple queues, fixing issue #93. This required the following changes:
* The `Command` structs were moved out of the `Queue` class, although I've kept them in the same file.
* Added a `Queue::execute()` method, which executes a given command **in its queue**, but only after it recursively executes the commands associated with the events in its wait list  (**in their own queues**). If the queue is in-order, the event associated with the previous command in the queue is added to the wait list as an additional dependency. For now this is assumed to be true, but now it's very simple to implement out of order queues (I have actually [done this already](https://github.com/fakenmc/Oclgrind/tree/ooo_queues), and will submit the patch if this pull request is …
> Add support for multiple queues

- src/core/WorkItem.cpp
- src/core/WorkItem.h
The fneg instruction seems to have been added to LLVM 8 with [this commit](https://github.com/llvm/llvm-project/commit/cbde0d9c7be1991751dc3eb5928294d2e00ef26a).
> Add fneg Instruction

- .travis-deps.sh
- .travis.yml
- CMakeLists.txt
- src/core/Program.cpp
The code changes required for LLVM10 seem to be fairly trivial. I'm not knowledgeable, so they might not be quite right (beyond compiling).
I also made some more non-trivial changes to the buildsystem/CI to test out that everything still works. It seems to build and pass tests on the CI and locally, but let me know if it can be improved!
> Updates for LLVM10

- src/plugins/Uninitialized.cpp
It seems that FNeg support was added to core in 5bcf3f1853c666ad5361604a75bb5d0449276193, but it is missing in Uninitialized.  Which in my case leads to such errors:
```
OCLGRIND FATAL ERROR (/home/vsevak/oclgrind/src/plugins/Uninitialized.cpp:1725)
Unsupported instruction: fneg
Kernel: k_tersoff_zbl_three_end
Entity: Global(1728,0,0) Local(0,0,0) Group(27,0,0)
%fneg = fneg float %122, !dbg !279
At line 1951 (column 19) of input.cl:
mdelr1[0] = -delr1[0];
```
The proposed patch is trivial and looks like solving the error (tests 98 out of 98), but since it is the only UnaryOperator there I ask you to review the changes.
> Add FNeg instruction to Uninitialized

- src/core/WorkItem.cpp
- src/core/WorkItem.h
In case of LLVM instruction `freeze`, just copy value as a no-op, as _"All uses of a 'freeze' instruction are guaranteed to always observe the same value."_
[https://reviews.llvm.org/D29121](url)
[https://llvm.org/docs/LangRef.html#freeze-instruction](url)
> Add support for LLVM 'freeze' instruction: treat as no-op.

- .github/workflows/ci.yml
- .github/workflows/install-deps.sh
- NEWS
- src/core/WorkItemBuiltins.cpp
- src/plugins/Uninitialized.cpp
This makes `Oclgrind` compile on LLVM 14. I ran it through the `pyopencl` test suite and it didn't segfault, so it should be reasonably ok.
Not sure about the changes to `ci.yaml`, so let me know if you want those reverted / changed somehow!
> Support LLVM 14
